# Generated by Django 5.1.3 on 2024-12-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='availability_date',
            field=models.DateTimeField(),
        ),
    ]
