# Generated by Django 5.1.3 on 2025-01-15 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='healthcare_professional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.healthcareprofessional'),
            preserve_default=False,
        ),
    ]
